language: rust
os: linux
dist: xenial

addons:
  postgresql: "12.6"
  apt:
    packages:
      - awscli
      - postgresql-12
      - postgresql-client-12

cache: cargo
before_cache:
    - find ./target/debug -type f -maxdepth 1 -delete
    - rm -fr ./target/debug/{deps,.fingerprint}/{dispatcher-*,*serde_test*}
    - rm -f  ./target/.rustc_info.json
    - rm -f ./target/sqlx/query-*.json

services:
  - docker
  - postgresql

git:
  depth: 1

install:
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main

jobs:
  include:
    - stage: check
      name: Format
      before_install:
        - rustup component add rustfmt
      script: cargo fmt -- --check

    - stage: check
      name: Lint
      before_install:
        - rustup component add clippy
      script: cargo clippy
      env:
        - CARGO_INCREMENTAL=0

    - stage: check
      name: Compilation
      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/dispatcher.test
        - CARGO_INCREMENTAL=0

      script:
        - cargo install sqlx-cli --version 0.5.2
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo build

    # Note: there isn't any doc yet.
    # - stage: build
    #   name: Docs
    #   install: cargo install mdbook --vers ^0.4
    #   script:
    #     - ./deploy.init.sh
    #     - mdbook build docs
    #     - ./deploy/ci-mdbook.sh
    - stage: build
      name: Build
      script:
        - ./deploy.init.sh
        - ./deploy/ci-install-tools.sh
        - ./deploy/ci-build.sh

stages:
  - name: check
  - name: build
    if: branch = master AND type = push

notifications:
  email: false
