language: rust
os: linux
dist: xenial

addons:
  apt:
    packages:
      - awscli

cache: cargo

services:
  - docker

git:
  depth: 1

jobs:
  include:
    - stage: check
      name: Format
      before_install:
        - rustup component add rustfmt
      script: cargo fmt -- --check

    - stage: check
      name: Lint
      before_install:
        - rustup component add clippy
      script: cargo clippy

    - stage: check
      name: Compilation
      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/dispatcher.test

      script:
        - cargo install sqlx-cli --version 0.2.0
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo build

    # Note: there isn't any doc yet.
    # - stage: build
    #   name: Docs
    #   install: cargo install mdbook --vers ^0.4
    #   script:
    #     - ./deploy.init.sh
    #     - mdbook build docs
    #     - ./deploy/ci-mdbook.sh
    - stage: build
      name: Build
      script:
        - ./deploy.init.sh
        - ./deploy/ci-install-tools.sh
        - ./deploy/ci-build.sh

stages:
  - name: check
  - name: build
    if: branch = master AND type = push

notifications:
  email: false
