id = "dispatcher.dev.svc.example.org"
agent_label = "alpha"
broker_id = "mqtt-gateway.dev.svc.example.org"

default_frontend_base = "http://test.example.org"

tenants = ["test.example.org"]

[authn."dev.svc.example.org"]
audience = ["dev.svc.example.org"]
algorithm = "ES256"
key = "data/keys/svc.public_key.p8.der.sample"

[authz."dev.svc.example.org"]
type = "localwhitelist"
[[authz."dev.svc.example.org".records]]
subject_account_id = "devops.dev.svc.example.org"
object = ["scopes"]
action = "rollback"

[conference_client]
account_id = "conference.dev.svc.example.org"
timeout = "5"
api_version = "v1"

[event_client]
account_id = "event.dev.svc.example.org"
timeout = "5"
api_version = "v1"

[tq_client]
base_url = "http://localhost:3000/"
timeout = 5
account_id = "event.dev.svc.example.org"
api_version = "v1"

[id_token]
algorithm = "ES256"
key = "data/keys/svc.private_key.p8.der.sample"

[mqtt]
uri = "mqtt://0.0.0.0:1883"
clean_session = false
incoming_message_queue_size = 10000000
outgoing_message_queue_size = 10000000
max_message_size = 100000
reconnect_interval = 3

[http]
listener_address = "0.0.0.0:3000"

[storage]
base_url = "mqtt://0.0.0.0:1883"
