apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/dispatcher-migration
    docker:
      dockerfile: docker/migration.dockerfile
  - image: foxford/dispatcher
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: dispatcher
        chartPath: chart
        artifactOverrides:
          app.image: foxford/dispatcher
          migrations.image: foxford/dispatcher-migration
        imageStrategy:
          helm: {}
        valuesFiles:
          - deploy/values.yaml
