apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/dispatcher-migration
    docker:
      dockerfile: docker/migration.dockerfile
  - image: foxford/dispatcher
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  kustomize:
  helm:
    paths:
    releases:
    - deploy/k8s/overlays/ns
    - name: dispatcher
      chartPath: chart
      artifactOverrides:
        container.image: foxford/dispatcher
        container.migrations: foxford/dispatcher-migration
      imageStrategy:
        helm: {}
      valuesFiles:
        - deploy/values.yaml
