apiVersion: v1
kind: Service
metadata:
  name: {{ include "dispatcher.fullname" . }}-headless
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dispatcher.selectorLabels" . | nindent 4 }}
  clusterIP: None
