apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "dispatcher.name" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ include "dispatcher.ingressPath" . }}(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: {{ include "dispatcher.serviceName" $ }}
              servicePort: {{ .Values.service.ports.http }}
