apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dispatcher.fullname" . }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "dispatcher.selectorLabels" . | nindent 6 }}
