apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dispatcher.name" . }}
  labels:
    {{- include "dispatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  serviceName: {{ include "dispatcher.name" . }}-headless
  selector:
    matchLabels:
      {{- include "dispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dispatcher.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: init-{{ .Chart.Name }}-migration
          {{- with .Values.container }}
          image: "{{ .migrations.repository }}:{{ .migrations.tag | default .image.tag | default $.Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "dispatcher.name" . }}-credentials
                  key: database_url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: {{ .Values.service.ports.http }}
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/v1/healthz
              port: {{ .Values.service.ports.http }}
            failureThreshold: 10
            periodSeconds: 3
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dispatcher.name" . }}-environment
                  key: RUST_LOG
            - name: DATABASE_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dispatcher.name" . }}-environment
                  key: DATABASE_POOL_SIZE
            - name: DATABASE_POOL_IDLE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dispatcher.name" . }}-environment
                  key: DATABASE_POOL_IDLE_SIZE
            - name: DATABASE_POOL_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dispatcher.name" . }}-environment
                  key: DATABASE_POOL_TIMEOUT
            - name: DATABASE_POOL_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dispatcher.name" . }}-environment
                  key: DATABASE_POOL_MAX_LIFETIME
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-{{ include "dispatcher.name" . }}-credentials
                  key: database_url
            - name: APP_AGENT_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            {{- with .Values.svc }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "dispatcher.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- range .Values.audiences }}
            {{- $audience := .audience }}
            {{- range $secret, $mounts := .credentials }}
            {{- range $mounts }}
            - name: {{ include "dispatcher.volumeMountName" (list $audience $secret) }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: dispatcher-config
        {{- with .Values.svc }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "dispatcher.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
        {{- range .Values.audiences }}
        {{- $audience := .audience }}
        {{- range $secret, $mounts := .credentials }}
        - name: {{ include "dispatcher.volumeMountName" (list $audience $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
