---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
{{- range $ports := .Values.app.svc_ports }}
    - name: {{ $ports.name }}
      port: {{ $ports.port }}
      targetPort: {{ $ports.targetPort }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  labels:
    prometheus.deckhouse.io/custom-target: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  clusterIP: None
  ports:
{{- range $ports := .Values.app.svc_ports }}
    - name: {{ $ports.name }}
      port: {{ $ports.port }}
      targetPort: {{ $ports.targetPort }}
{{- end }}
