app:
  hpa:
    min_replicas:
      _default: "2"
    max_replicas:
      _default: "4"
    average_utilization:
      _default: "80"
  init_resources:
    cpu:
      ng:
        classroom:
          _default: 0.01
    memory:
      ng:
        classroom:
          _default: 100Mi
  resources:
    cpu:
      ng:
        classroom:
          _default: 0.5
          production: 2
          staging01: 0.5
          testing01: 0.5
          testing02: 0.5
          testing03: 0.5
    memory:
      ng:
        classroom:
          _default: 500Mi
          production: 1Gi
          staging01: 500Mi
          testing01: 500Mi
          testing02: 500Mi
          testing03: 500Mi
